### ISSUE TITLE
buy script doesn't run

### ISSUE THREAD

**Issue by RyanSinger** [phelixnmc/antpy#1]
Ryans-MacBook-Pro:antpy ryan$ python ant_buyer.py
Traceback (most recent call last):
  File "ant_buyer.py", line 8, in <module>
    rpc = namerpc.CoinRpc()
  File "/Users/ryan/antpy/namerpc.py", line 50, in **init**
    options = self.get_options()
  File "/Users/ryan/antpy/namerpc.py", line 135, in get_options
    with open(self.lookup_conf_folder() + COINAPP + ".conf") as f:
  File "/Users/ryan/antpy/namerpc.py", line 120, in lookup_conf_folder
    dataFolder = path.join(os.environ["HOME"],
NameError: global name 'os' is not defined

Press <enter> for another round, <ctrl-c> to exit.
^CTraceback (most recent call last):
  File "ant_buyer.py", line 80, in <module>
    raw_input()
KeyboardInterrupt

**Comment by phelixbtc** [comment]
Thanks for posting this bug. Should be fixed now. (https://github.com/phelixnmc/antpy/commit/0169e6c11aebd52fe0ecf923b5262491f84e948c)

**Comment by RyanSinger** [comment]
Thanks!
